[package]
name = "std_library_types"
version = "0.1.0"
authors = ["Ryosuke YASUOKA <yasuoka0830@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
